### ISSUE TITLE
issue when try to run sobelow/action@v1 on pipeline

### ISSUE THREAD

**Issue by murilobauerc** [sobelow/action#1]
Hello ✋🏻 ! 
I'm using sobelow as one of my pipeline steps and when I ran it gives me the following error: 

warning: you must append "/github/home/.mix/escripts" to your PATH if you want to invoke escripts by name

** (ArgumentError) unknown application: :castore
    (elixir 1.11.2) lib/application.ex:896: Application.app_dir/1
    (elixir 1.11.2) lib/application.ex:923: Application.app_dir/2
    (sobelow 0.12.1) lib/sobelow.ex:552: Sobelow.get_sobelow_version/0
    (sobelow 0.12.1) lib/sobelow.ex:581: Sobelow.maybe_prompt_update/2
    (sobelow 0.12.1) lib/sobelow.ex:34: Sobelow.run/0
    (elixir 1.11.2) lib/kernel/cli.ex:124: anonymous fn/3 in Kernel.CLI.exec_fun/2

This is how I set up sobelow:
```    
jobs:
  code-analysis:
    name: Code Analysis
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Run Sobelow
        uses: sobelow/action@v1
        with:
          report: false
          flags: --config
```
